name: Flake Checks

on:
  push:
  pull_request:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Formatting and lint checks
        run: >-
          nix --extra-experimental-features 'nix-command flakes'
          build --print-build-logs
          .#checks.x86_64-linux.formatting
          .#checks.x86_64-linux.statix
          .#checks.x86_64-linux.deadnix
      - name: Evaluate system configuration
        run: >-
          nix --extra-experimental-features 'nix-command flakes'
          eval --raw
          .#nixosConfigurations.AKATOSH.config.system.build.toplevel.drvPath
